# Site settings
title: Cohen-Nicoleau 
email: lewis.cohen@cohen-nicoleau.com
description: "Miami based law firm specializing in banking, finance, and commerical litigation."
baseurl: ""
#url: "http://cohen-nicoleau.com"
url: "http://www.thezymologist.com/law"
#url: "http://localhost:4000"

# Build settings
markdown: redcarpet
permalink: pretty
